---
spring:
  config:
    activate:
      on-profile: dev

application:
  client-origin-url: http://localhost:3000

server:
  error:
    whitelabel:
      enabled: false
  port: 8080

  web:
    resources:
      add-mappings: false

okta:
  oauth2:
    issuer: https://dev-v1031rsex2ls46o4.us.auth0.com/
    audience: https://myapi.demo.com
...
