---
spring:
  config:
    activate:
      on-profile: dev

application:
  client-origin-url: http://localhost:3000

server:
  error:
    whitelabel:
      enabled: false
  port: 8080

  web:
    resources:
      add-mappings: false

okta:
  oauth2:
    issuer: https://<auth0-domain>/
    audience: api-identifier
...
